# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer
import tkinter
from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage
from tkinter import ttk

import os


def client_repertoire_menu(window, buy_f, back_f, repertoire_options, repertoire_list_on_select):
    executable_path = os.path.abspath(__file__)
    executable_directory = os.path.dirname(executable_path)
    widgets = {}

    def relative_to_assets(path: str) -> Path:
        return executable_directory + "/assets/client_repertoire_menu/" + path

    window.geometry("800x600")
    window.configure(bg="#AE7043")

    canvas = Canvas(
        window,
        bg="#AE7043",
        height=600,
        width=800,
        bd=0,
        highlightthickness=0,
        relief="ridge"
    )

    canvas.place(x=0, y=0)
    image_image_1 = PhotoImage(
        file=relative_to_assets("image_1.png"))
    image_1 = canvas.create_image(
        389.0,
        300.0,
        image=image_image_1
    )
    widgets['image_image_1'] = image_image_1

    options = ['амфитеатр', 'высокий партер', 'ложа', 'партер']
    combo_box = ttk.Combobox(canvas, values=options)
    combo_box.place(x=369, y=509, width=109, height=36)
    widgets['combo_box_place'] = combo_box

    canvas.create_rectangle(
        50.0,
        52.0,
        354.0,
        548.0,
        fill="#D9D9D9",
        outline="")

    listbox = tkinter.Listbox(canvas)
    for option in repertoire_options:
        listbox.insert(tkinter.END, option)

    listbox.bind('<<ListboxSelect>>', repertoire_list_on_select)
    listbox.place(x=50, y=52, width=304, height=496)
    widgets['listbox_repertoire'] = listbox

    button_image_1 = PhotoImage(
        file=relative_to_assets("button_1.png"))
    button_1 = Button(
        image=button_image_1,
        borderwidth=0,
        highlightthickness=0,
        command=back_f,
        relief="flat"
    )
    button_1.place(
        x=624.0,
        y=38.0,
        width=141.0,
        height=13.0
    )
    widgets['button_image_1'] = button_image_1
    widgets['button_back'] = button_1

    canvas.create_rectangle(
        648.0,
        42.0,
        688.0,
        44.0,
        fill="#D9D9D9",
        outline=""
    )

    button_image_2 = PhotoImage(
        file=relative_to_assets("button_2.png"))
    button_2 = Button(
        image=button_image_2,
        borderwidth=0,
        highlightthickness=0,
        command=buy_f,
        relief="flat"
    )
    button_2.place(
        x=611.0,
        y=509.0,
        width=132.0,
        height=39.0
    )
    widgets['button_image_2'] = button_image_2
    widgets['button_buy'] = button_2

    canvas.create_text(
        624.0,
        232.0,
        anchor="nw",
        text="Билеты",
        fill="#AE7043",
        font=("Ubuntu Bold", 16 * -1)
    )

    canvas.create_text(
        368.0,
        64.0,
        anchor="nw",
        text="Название:",
        fill="#AE7043",
        font=("Ubuntu Regular", 16 * -1)
    )

    canvas.create_text(
        368.0,
        106.0,
        anchor="nw",
        text="Дата:",
        fill="#AE7043",
        font=("Ubuntu Regular", 16 * -1)
    )

    canvas.create_text(
        368.0,
        148.0,
        anchor="nw",
        text="Автор:",
        fill="#AE7043",
        font=("Ubuntu Regular", 16 * -1)
    )

    canvas.create_text(
        368.0,
        190.0,
        anchor="nw",
        text="Жанр:",
        fill="#AE7043",
        font=("Ubuntu Regular", 16 * -1)
    )

    t = tkinter.Label(canvas, text='name_info')
    t.place(x=508, y=64)
    widgets["name_info"] = t

    t = tkinter.Label(canvas, text='date_info')
    t.place(x=508, y=106)
    widgets["date_info"] = t

    t = tkinter.Label(canvas, text='author_info')
    t.place(x=508, y=147)
    widgets["author_info"] = t

    t = tkinter.Label(canvas, text='genre_info')
    t.place(x=508, y=189)
    widgets["genre_info"] = t

    canvas.create_text(
        375.0,
        250.0,
        anchor="nw",
        text="Место",
        fill="#AE7043",
        font=("Ubuntu Bold", 16 * -1)
    )

    canvas.create_text(
        491.0,
        250.0,
        anchor="nw",
        text="Цена",
        fill="#AE7043",
        font=("Ubuntu Bold", 16 * -1)
    )

    canvas.create_text(
        584.0,
        250.0,
        anchor="nw",
        text="всего",
        fill="#AE7043",
        font=("Ubuntu Bold", 16 * -1)
    )

    canvas.create_text(
        666.0,
        250.0,
        anchor="nw",
        text="доступно",
        fill="#AE7043",
        font=("Ubuntu Bold", 16 * -1)
    )

    canvas.create_text(
        368.0,
        303.0,
        anchor="nw",
        text="амфитеатр",
        fill="#000000",
        font=("Inder Regular", 14 * -1)
    )

    t = tkinter.Label(canvas, text='11_info')
    t.place(x=495, y=303)
    widgets["11_info"] = t

    t = tkinter.Label(canvas, text='21_info')
    t.place(x=495, y=360)
    widgets["21_info"] = t

    t = tkinter.Label(canvas, text='31_info')
    t.place(x=495, y=418)
    widgets["31_info"] = t

    t = tkinter.Label(canvas, text='41_info')
    t.place(x=495, y=463)
    widgets["41_info"] = t

    t = tkinter.Label(canvas, text='42_info')
    t.place(x=600, y=463)
    widgets["42_info"] = t

    t = tkinter.Label(canvas, text='43_info')
    t.place(x=682, y=463)
    widgets["43_info"] = t

    t = tkinter.Label(canvas, text='32_info')
    t.place(x=600, y=418)
    widgets["32_info"] = t

    t = tkinter.Label(canvas, text='22_info')
    t.place(x=600, y=360)
    widgets["22_info"] = t

    t = tkinter.Label(canvas, text='23_info')
    t.place(x=682, y=360)
    widgets["23_info"] = t

    t = tkinter.Label(canvas, text='33_info')
    t.place(x=682, y=418)
    widgets["33_info"] = t

    t = tkinter.Label(canvas, text='12_info')
    t.place(x=600, y=303)
    widgets["12_info"] = t

    t = tkinter.Label(canvas, text='13_info')
    t.place(x=682, y=303)
    widgets["13_info"] = t

    canvas.create_text(
        368.0,
        358.0,
        anchor="nw",
        text="высокий ",
        fill="#000000",
        font=("Inder Regular", 14 * -1)
    )

    canvas.create_text(
        368.0,
        372.0,
        anchor="nw",
        text="партер",
        fill="#000000",
        font=("Inder Regular", 14 * -1)
    )

    canvas.create_text(
        368.0,
        418.0,
        anchor="nw",
        text="ложа",
        fill="#000000",
        font=("Inder Regular", 14 * -1)
    )

    canvas.create_text(
        368.0,
        463.0,
        anchor="nw",
        text="партер",
        fill="#000000",
        font=("Inder Regular", 14 * -1)
    )

    entry_image_1 = PhotoImage(
        file=relative_to_assets("entry_1.png"))
    entry_bg_1 = canvas.create_image(
        527.0,
        527.0,
        image=entry_image_1
    )
    entry_1 = Entry(
        bd=0,
        bg="#D9D9D9",
        fg="#000716",
        highlightthickness=0
    )
    entry_1.place(
        x=495.0,
        y=509.0,
        width=64.0,
        height=34.0
    )
    widgets['entry_image_1'] = entry_image_1
    widgets['entry_bg_1'] = entry_bg_1
    widgets['entry_n_tickets'] = entry_1

    window.resizable(False, False)

    return window, widgets
